### ISSUE TITLE
SplitIO does not seem to be properly imported into the files

### ISSUE THREAD

**Issue by profaurore** [splitio/redux-client#130] opened 2024-11-15 02:37 UTC
I am working on a Typescript application that makes use of this package, and have been unable to the get Typescript types that use `SplitIO.*` to correctly resolve; they all resolve to `any`. Are there some imports that are missing?

For example,
```
// This should be `SplitIO.TreatmentWithConfig`, but produces `any`.
type LocalTreatmentWithConfig = ISplitState['treatments'][string][string];
```

**Comment by EmilianoSanchez** [comment] 2024-11-15 13:50
Hi @profaurore , 

The problem you have is that the `ISplitState` interface is not part of the `SplitIO` namespace, and so, you need to explicitly import it from the `@splitsoftware/splitio-redux` package (Redux SDK). For example:

```typescript
import { ISplitState } from '@splitsoftware/splitio-redux';

type LocalTreatmentWithConfig = ISplitState['treatments'][string][string];

const someTreatmentWithConfig: LocalTreatmentWithConfig = {
  treatment: 'on',
  config: null
};

// SplitIO.TreatmentWithConfig and LocalTreatmentWithConfig are the same types
const sameTreatmentWithConfig: SplitIO.TreatmentWithConfig = someTreatmentWithConfig;
```

Note that the `SplitIO` namespace, unlike `ISplitState`, is available automatically when importing any Split SDK. But if you prefer, you can import it explicitly as follows: `import SplitIO from '@splitsoftware/splitio/types/splitio';`


The `SplitIO` namespace is defined in the `@splitsoftware/splitio` package, which is the base JavaScript SDK that the Redux SDK (`@splitsoftware/splitio-redux` package) extends from. And Redux SDK exports a few more types and interfaces, like `ISplitState`, that we weren't able to merge into the namespace (due to some conflicts with CommonJS module system) and so they are not part of it. 

You can check [this line](https://github.com/splitio/redux-client/blob/master/src/index.ts#L12), for the complete list of TypeScript definitions that the Redux SDK exports but are not part of the namespace:

```typescript
// Types
import type { IStatus, ISplitState, IGetSplitState, IInitSplitSdkParams, IGetTreatmentsParams, IDestroySplitSdkParams, ITrackParams } from '@splitsoftware/splitio-redux';
```

**Comment by profaurore** [comment] 2024-11-16 05:08
Hi @EmilianoSanchez, thank you for the prompt response.

I must have a Typescript configuration that is interfering with the namespace import.

If I do the following, the resulting type is `any`.

```ts
import type { ISplitState } from '@splitsoftware/splitio-redux';

type TestType = ISplitState['treatments'][string][string];
```

Whereas if I do the following, the resulting type is the expected `SplitIO.TreatmentWithConfig | undefined`.

```ts
import type { ISplitState } from '@splitsoftware/splitio-redux';
import type SplitIO from '@splitsoftware/splitio/types/splitio';

type TestType = ISplitState['treatments'][string][string];
```

I'll take a closer look on Monday and report back any findings in case others run into the same problem. Feel free to close this issue beforehand, if appropriate.

**Comment by EmilianoSanchez** [comment] 2024-11-19 12:10
Thanks @profaurore for sharing!

Unfortunately, I couldn't reproduce it on my side. Could you share the version of the Redux SDK (`npm ls @splitsoftware/splitio-redux`) and TypeScript (`npm ls typescript`) you are using? Or any TS configuration option that you consider relevant for the problem?

**Comment by profaurore** [comment] 2024-12-04 22:39
I have setup a minimal reproduction of the issue.

https://github.com/profaurore/redux-client-issue-130

**Comment by EmilianoSanchez** [comment] 2024-12-05 20:47
Hey @profaurore , 

I am able to reproduce it with your example! Thank you. 
I was wrongly using a project with other Split SDK dependencies, so the SplitIO namespace was being imported from another package. 

We just did the release of React SDK v2.0.1 with a fix. So I will be closing this issue now, but feel free to reopen it if you cannot fix it with the new version.

**Closed by EmilianoSanchez** 2024-12-05 20:47 UTC
